// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUH1rivZz3GMVs2_FTva7yUcku_wPq-cE',
    appId: '1:594869209525:web:4115008bf118e4f1e6b1fc',
    messagingSenderId: '594869209525',
    projectId: 'lockedin-558fd',
    authDomain: 'lockedin-558fd.firebaseapp.com',
    storageBucket: 'lockedin-558fd.firebasestorage.app',
    measurementId: 'G-0J3EJZYF1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ62WO2SbS5qv4pvoqLzArdamXs-tmf10',
    appId: '1:594869209525:android:5008dfefd93fe9cbe6b1fc',
    messagingSenderId: '594869209525',
    projectId: 'lockedin-558fd',
    storageBucket: 'lockedin-558fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKRlH6PQJq970_VxeDXxfzo3XlXRyOIJs',
    appId: '1:594869209525:ios:265046e3bb3b5133e6b1fc',
    messagingSenderId: '594869209525',
    projectId: 'lockedin-558fd',
    storageBucket: 'lockedin-558fd.firebasestorage.app',
    iosBundleId: 'com.example.lockedin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKRlH6PQJq970_VxeDXxfzo3XlXRyOIJs',
    appId: '1:594869209525:ios:265046e3bb3b5133e6b1fc',
    messagingSenderId: '594869209525',
    projectId: 'lockedin-558fd',
    storageBucket: 'lockedin-558fd.firebasestorage.app',
    iosBundleId: 'com.example.lockedin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUH1rivZz3GMVs2_FTva7yUcku_wPq-cE',
    appId: '1:594869209525:web:7fc77334225a0330e6b1fc',
    messagingSenderId: '594869209525',
    projectId: 'lockedin-558fd',
    authDomain: 'lockedin-558fd.firebaseapp.com',
    storageBucket: 'lockedin-558fd.firebasestorage.app',
    measurementId: 'G-MEFSBC4PFP',
  );
}
